# Usar una imagen base de Node.js
FROM node:16-alpine

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm ci

# Copiar el resto de los archivos del proyecto
COPY . .

# Construir la aplicación
RUN npm run build

# Exponer el puerto en el que la aplicación correrá
EXPOSE 3001

# Comando para correr la aplicación
CMD ["npm", "start"]
