"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
// import { defineConfig } from "prisma/config";
// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
